parameters:
#    contactos.example.class: Eventos\ContactosBundle\Example

services:
#    contactos.example:
#        class: %contactos.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
