contacto:
    path:     /
    defaults: { _controller: "ContactosBundle:Contacto:index" }

contacto_inicio:
    path:     /inicio
    defaults: { _controller: "ContactosBundle:Contacto:inicio" }

contacto_show:
    path:     /{id}/show
    defaults: { _controller: "ContactosBundle:Contacto:show" }

contacto_new:
    path:     /new
    defaults: { _controller: "ContactosBundle:Contacto:new" }

contacto_create:
    path:     /create
    defaults: { _controller: "ContactosBundle:Contacto:create" }
    requirements: { _method: post }

contacto_edit:
    path:     /{id}/edit
    defaults: { _controller: "ContactosBundle:Contacto:edit" }

contacto_update:
    path:     /{id}/update
    defaults: { _controller: "ContactosBundle:Contacto:update" }
    requirements: { _method: post|put }

contacto_delete:
    path:     /{id}/delete
    defaults: { _controller: "ContactosBundle:Contacto:delete" }
    requirements: { _method: post|delete }
